apiVersion: v1
kind: Service
metadata:
  name: py-app-svc
  namespace: default
  labels:
    app: py-app
spec:
  type: NodePort 
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000  # Adjust if your Node.js app is running on a different port
      nodePort: 30008
  selector:
    app: py-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: py-app
  namespace: default
  labels:
    app: server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: py-app
  template:
    metadata:
      labels:
        app: py-app
    spec:
      containers:
      - name: py-app
        image: bjnandi/python-crud-app:v1.0.117
        ports:
        - containerPort: 8000
        # env:
        # - name: CLOUDINARY_CLOUD_NAME
        #   value: "duwjbcn5x"

        # - name: CLOUDINARY_API_KEY
        #   value: "246694643839175"

        # - name: CLOUDINARY_API_SECRET
        #   value: "EFA0Qj8tD0f2-u_3Adx2I8ndHaY"

        # - name: DB_USER
        #   value: myuser

        # - name: DB_PASSWORD
        #   value: mypassword

        # - name: DB_HOST  #aaaaasshhsssssshhdddddddddddddd
        #   value: mongodb-0.mongodb-svc.default.svc.cluster.local